---
title: "Quarto articles"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Notes on getting quarto to build articles with pkgdown:

1) see this error page: https://github.com/r-lib/pkgdown/issues/2733
2) This will lead you to Ethan Bass' repository: https://github.com/ethanbass/quartoArticleError/blob/master/DESCRIPTION

You need to install his version of pkgdown - note this may have been fixed since I wrote this, so check that pkgdown now supports his patches.\

1) `use_pkgdown()`
2) create arciles - note I have not had luck using either the `use_vignette()` or `use_article()` functions to set this up. Instead I make /vignettes and /vignettes/articles directories, add .quarto to the main .gitignore and ^vignettes/articles$ to .Rbuildignore. I also create a vignettes/.gitignore with *.html,
*.R, /.quarto/ (note do not add ',' in actual file).
3) `use_pkgdown_github_pages()` to set up the github actions workflow
4) change the defualt on line 37 from `extra-packages: any::pkgdown, local::.` to `extra-packages: github::ethanbass/pkgdown@qmd_articles, local::.` to make sure the patched version of pkgdown is used for the build. This will ensure quarto articles are rendered in the correct place for pkgdown to find them when building the site.


